In [2]:
import pymysql
import numpy as np
import pandas as pd

In [3]:
# 데이터베이스 연결
conn = pymysql.connect(user='data', password='data1234', 
                       host='localhost', db='djangoseouldb', charset='utf8')

curs = conn.cursor(pymysql.cursors.DictCursor)

In [3]:
gu_data = ['종로구','중구','용산구','성동구','광진구','동대문구','중랑구','성북구','강북구','도봉구','노원구','은평구','서대문구','마포구','양천구','강서구','구로구','금천구','영등포구','동작구','관악구','서초구','강남구','송파구','강동구']
gu_locx = [60, 60, 60, 61, 62, 61, 62, 61, 61, 61, 61, 59, 59, 59, 58, 58, 58, 59, 58, 59, 59, 61, 61, 62, 62]
gu_locy = [127, 127, 126, 127, 126, 127, 128, 127, 128, 129, 129, 127, 127, 127, 126, 126, 125, 124, 126, 125, 125, 125, 126, 126, 126]
gu_dict = {'gu_name': gu_data, 'gu_locx': gu_locx, 'gu_locy': gu_locy}

gu_data = pd.DataFrame(gu_dict)

data_set=[]
for a, b, c in gu_data.to_records(index=False):
    data_set.append((a, int(b), int(c)))

In [7]:
# 구 데이터 insert
sql_g = """
    INSERT into tour_gu (gu_name, gu_locx, gu_locy)
    values (%s, %s, %s)
    """

curs.executemany(sql_g, tuple(data_set))
conn.commit()

In [8]:
category_data = ['수목원', '동물원', '유적지', '박물관', '거리', '공원']

# 카테고리 insert
sql_c = """
    INSERT into tour_category (category_name)
    values (%s)
    """

curs.executemany(sql_c, category_data)
conn.commit()

In [9]:
data = pd.read_csv('raw_data.csv')
data = data[data.isnull()['소개']==False]
display(data)

,index,명칭,행정 구,분류3,행정구 번호,카테고리 번호,상세주소,이미지 URL,소개
0,1,국립고궁박물관,종로구,박물관,1,4,서울 종로구 세종로 1-57,https://search2.kakaocdn.net/argon/130x130_85_...,"국립고궁박물관(國立古宮博物館, National Palace Museum of Kor..."
1,2,대한민국역사박물관,종로구,박물관,1,4,서울 종로구 세종로 82-1,https://search1.kakaocdn.net/argon/130x130_85_...,"대한민국역사박물관(大韓民國歷史博物館, National Museum of Korean..."
2,4,명인박물관,종로구,박물관,1,4,서울 종로구 가회동 208-7,https://search2.kakaocdn.net/argon/130x130_85_...,"경희대학교(慶熙大學校, Kyung Hee University)는 1911년에 개교한..."
3,5,민속박물관,종로구,박물관,1,4,서울 종로구 세종로 1-1,https://search3.kakaocdn.net/argon/130x130_85_...,"국립민속박물관(國立民俗博物館, National Folk Museum of Korea..."
4,6,부엉이박물관,종로구,박물관,1,4,서울 종로구 삼청동 27-2,https://search2.kakaocdn.net/argon/130x130_85_...,부엉이 박물관은 대한민국 서울특별시 종로구 삼청동에 자리한 박물관이다. 삼청동 감사...
...,...,...,...,...,...,...,...,...,...
397,127,둘레길2구간,성북구,거리,8,5,서울시 성북구 성북동 일대,https://search3.kakaocdn.net/argon/130x130_85_...,지방도 제1023호선(화개 ~ 함양선)은 경상남도 하동군 화개면 화개삼거리와 경상남...
398,129,먹거리촌,금천구,거리,18,5,서울시 금천구 가산동 일대,https://search4.kakaocdn.net/argon/130x130_85_...,정발산동(鼎鉢山洞)은 경기도 고양시 일산동구에 있는 행정동 및 법정동이다.\n\n
399,130,방이동모텔촌,송파구,거리,24,5,서울시 송파구 방이2동 일대,https://search4.kakaocdn.net/argon/130x130_85_...,방이동모텔촌
400,131,석촌호수길,송파구,거리,24,5,서울시 송파구 석촌동 일대,https://search4.kakaocdn.net/argon/130x130_85_...,석촌호수공원(石村湖水公園)은 서울특별시 송파구 잠실동에 있는 공원이다. 송파나루공원...
401,132,문정동로데오거리,송파구,거리,24,5,서울시 송파구 문정1동 일대,https://search1.kakaocdn.net/argon/130x130_85_...,문정로데오거리는 서울특별시 송파구 문정1동에 위치한 패션 특화 거리이다.\n약 20...

In [10]:
sql_ts = """
    INSERT into tour_toursite (toursite_name, toursite_address, toursite_img, toursite_detail, category_id, gu_id)
    values (%s, %s, %s, %s, %s, %s)
    """

data_set=[]
for a, b, c, d, e, f, g, h, i in data.to_records(index=False):
    data_set.append((b, g, h, i, f, str(e)))

In [11]:
curs.executemany(sql_ts, tuple(data_set))
conn.commit()

In [ ]:
conn.close()

- toursite update sql

In [18]:
sql_up = """
    UPDATE `tour_toursite` SET `toursite_address` = %s WHERE `toursite_name` = %s;
    """

In [6]:
street_data = pd.read_csv('data/data/street.csv', encoding='CP949')
for i in range(len(street_data)):
    street_data.loc[i:,['상세주소']]= '{"상세주소":"'+street_data['지번 주소'][i]+'", "x":'+str(street_data['중심 좌표 X'][i])+', "y":'+str(street_data['중심 좌표 Y'][i])+'}'
street_df = street_data[['최종 표기명', '행정 구', '상세주소']].copy()
street_df.columns = ['명칭', '행정 구', '상세주소']
street_df['분류3'] = '거리'
display(street_df)

              명칭  행정 구                                               상세주소 분류3
0    서울신림동민속순대타운   관악구  {"상세주소":"서울시 관악구 서원동 일대", "x":126.9345984302, ...  거리
1         이대구제거리  서대문구  {"상세주소":"서울시 서대문구 신촌동 일대", "x":126.9465464425,...  거리
2            피맛골   종로구  {"상세주소":"서울시 종로구 종로1.2.3.4가동 일대", "x":126.9873...  거리
3         병천토속순대   강동구  {"상세주소":"서울시 강동구 길동 일대", "x":127.1470468799, "...  거리
4            능동로   광진구  {"상세주소":"서울시 광진구 능동 일대", "x":127.0824623102, "...  거리
..           ...   ...                                                ...  ..
129          장수길   성북구  {"상세주소":"서울시 성북구 삼선동 일대", "x":127.0207811637, ...  거리
130       둘레길2구간   성북구  {"상세주소":"서울시 성북구 성북동 일대", "x":126.9921504705, ...  거리
131     둘레길순례길구간   강북구  {"상세주소":"서울시 강북구 우이동 일대", "x":126.9832661, "y"...  거리
132        고향의거리   양천구  {"상세주소":"서울시 양천구 신정6동 일대", "x":126.8629865421,...  거리
133      왕십리곱창골목    중구  {"상세주소":"서울시 중구 황학동 일대", "x":127.0204336493, "...  거리

[134 rows x 4 columns]

In [16]:
data_set=[]
for a, b, c, d in street_df.to_records(index=False):
    data_set.append((str(c), a))

In [19]:
curs.executemany(sql_up, tuple(data_set))
conn.commit()

In [12]:
conn.close()